service:
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
   service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
   service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
   externalTrafficPolicy: Local
   type: LoadBalancer