provider: aws
aws:
  zoneType: public
txtOwnerId: ${text_owner_id}
domainFilters: 
  - ${domain_filters}
policy: sync
registry: txt
logLevel: debug #for detailed logs
serviceAccount:
  create: true
  name: external-dns
  annotations: 
    eks.amazonaws.com/role-arn: ${external_dns_role}

  